#####################################################################################################
#                                               GENERAL                                             #
#####################################################################################################
locate_within: 500         #Number of blocks in the area that should be checked for the queried biome